### ISSUE TITLE
1.19.2 - Server Kicked Client when Dismantling and Said this (See Screenshot)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AlexiyOrlov/k-turrets#10]
![N7cVEYo 1](https://user-images.githubusercontent.com/10351221/201554659-bea7f7d6-07e2-4bd8-be83-d416e124fe0c.png)

Also now all turrets that are dismantled claims (You don't own this) and none admins cannot pick them up.

**Comment by AlexiyOrlov** [comment]
Closing as outdated
