### ISSUE TITLE
1.18.2 feature request - more vertical range

### ISSUE THREAD

**Issue by systemshaper** [AlexiyOrlov/k-turrets#14]
These turrets would be a great solution to allow building defensive towers, like classic arrow towers from RTS games, or used for air defense against phantoms and the like. Unfortunately they seem to only be able to target mobs about 5 blocks above or below themselves. It would be wonderful if their vertical range could be improved, either to match their horizontal range, or at least to a larger base value.
Thanks for your consideration!

**Comment by AlexiyOrlov** [comment]
Done
