### ISSUE TITLE
[1.16.5] Titanium ore entirely missing its datapack

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#16]
No texture, no drop, only generation.  Please remove it from the registry if the block is meant to be deprecated, or remove the block's generation until the block is completed.

The log spits this when broken:
`[12Sep2023 20:41:24.807] [main/WARN] [net.minecraftforge.common.ForgeHooks/]: Picking on: [BLOCK] k-turrets:titanium_ore gave null item`

![image](https://github.com/AlexiyOrlov/k-turrets/assets/82226641/6cbd5bf2-dbcb-469c-a573-e8daf27a2526)

**Comment by AlexiyOrlov** [comment]
It is meant to replace steel in recipes, but I forgot to finish it. Fixed now.
