### ISSUE TITLE
[1.16.5] Drones missing language pack names for nametags

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#17]
Demonstrated via ToroHealth, the names of all drones are just the namespaces, they need english language pack definitions.

![2023-09-12_20 46 42](https://github.com/AlexiyOrlov/k-turrets/assets/82226641/f61afece-ddc8-4b97-80d4-1f4065778f34)

**Comment by AlexiyOrlov** [comment]
Should be fixed

**Comment by NighthowlerStudios** [comment]
Sure did.
