### ISSUE TITLE
[Enhancement] Please consider dropping config fire rate range minimum from 10 ticks to 1 tick

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#18]
My modpack's game design supports and includes rapid fire rate weapons.  However, none of your drones nor turret configurations support any firerates faster than 10 ticks per shot.  Please consider changing the range boundaries in the config to have the firerate lower to the server tick rate minimum (1 tick per shot), but keep your current values.  With the new range of configuration I will feel more free to configure as I please.

If there are any other underlying issues with why the 10 ticks per shot configuration is set, I might be able to take a look.

**Comment by AlexiyOrlov** [comment]
It's 10 ticks because that's how long mob invulnerability time is, but I can lower it.

**Comment by NighthowlerStudios** [comment]
It would be greatly appreciated, me and a lot of other modpacks utilize a mod called NoDami which removes iFrames (unless the modpacker configures certain damage types and mob sources out).  For my pack, projectile damage has no invulnerability frames.  So being able to use high fire rate turrets makes sense.

**Comment by AlexiyOrlov** [comment]
It has been done
