### ISSUE TITLE
[1.16.5] Turret config will not set turret health

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#19]
I have mine set to 20 but it keeps resetting to 60 in world.  It's possible the config is being loaded at the wrong time.  Forge registers configs in a very strange way by default.

**Comment by NighthowlerStudios** [comment]
Closed because it seemed to be my fault.  No clue if it has an issue if the save file loads a new one or not.  Better safe than sorry.

**Comment by NighthowlerStudios** [comment]
Reopening this issue because it ended up not my fault, something keeps resetting the configs quite reliably when the game reloads.

**Comment by AlexiyOrlov** [comment]
Config should work now, correct one is named 'k-turrets-common'
