### ISSUE TITLE
[Enhancement] All projectiles travel invisibly fast, consider speed configuration

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#20]
I don't know which update did it, but brick projectiles etcetera now only show up for one tick, then immediately zoom to the target the next tick, making their accuracy godsent.  Is this a bug, or intended?  If intended, can we please have a speed cap so players can still dodge?

**Comment by AlexiyOrlov** [comment]
I will make an option for speed

**Comment by AlexiyOrlov** [comment]
Implemented
