### ISSUE TITLE
Projectiles still launch absurdly fast due to acceleration applying per tick

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#22]
Even if I set the config down from 50 to just 1, projectiles are still blindingly fast.  I am convinced this is a bug due to motion code with the projectiles.  If I set it to a very low value I can watch projectiles suddenly start slow then zip into a super fast speed.

**Comment by AlexiyOrlov** [comment]
Should be fixed
