### ISSUE TITLE
No language pack for Turrets "no turrets nearby"

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#23]

**Comment by AlexiyOrlov** [comment]
When this message appears?

**Comment by NighthowlerStudios** [comment]
When you hit the keybind for "Locate Drones/Turrets", the new feature meant to highlight them, if you never spawned any a message appears in the top of the screen, with an id string similar to "no turrets nearby".  will you need the full id for the translation pack?

**Comment by AlexiyOrlov** [comment]
It should be like "k_turrets.no.drones.nearby" or "There are no drones in 64 block radius"

**Comment by NighthowlerStudios** [comment]
it only shows "k_turrets.no.drones.nearby".  that's what I mean by a missing translation/language pack id.
