### ISSUE TITLE
[1.16.5] Titanium Ore is so common it chokes out Coal Ore generation

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#24]
![image](https://github.com/AlexiyOrlov/k-turrets/assets/82226641/ee3ecdee-8d8d-4fe3-b98b-e0f1e6b73c25)

If your mod is trying to generate ores by replacing blocks, please don't.  Please learn to use a proper ore generation class.  What happens right now is all of the veins that would have originally been coal become titanium 99% of the time. I feel like this is backwards from the intended generation rate.

**Comment by AlexiyOrlov** [comment]
My ore DOESN'T replace other ore on purpose. I am using proper generation methods. All I can do is add an option for ore frequency.

**Comment by NighthowlerStudios** [comment]
Are you sure it's not more than intended?  I was getting around 10 veins within line of sight within a mere 64 block radius range :/

And yet, when I go deeper into the world, coal overtakes commonality back away from titanium and titanium becomes rare again

**Comment by AlexiyOrlov** [comment]
Made ore amount configurable - use k_turrets.properties file to set it.

**Comment by NighthowlerStudios** [comment]
I was able to turn it down to a rarity I appreciate which was of 1 instead of the default 5.  I may raise it a little later but now coal is finally spawning close to the surface again instead of titanium choking out its generators.
