### ISSUE TITLE
Game crashes -- crash report included

### ISSUE THREAD

**Issue by glowguy** [AlexiyOrlov/k-turrets#29]
1.19.2 Forge, latest version

I have an issue while firing a cobble turret that is hidden behind lava. The turret still targets mobs and fires at them, but sometimes, my game crashes because of this. I have isolated the issue as I can replicate the problem being when I place and fire the turret from behind lava.

The turrets work fine when not behind lava.

Crash report: 
[crash-2023-12-20_22.09.27-server.txt](https://github.com/AlexiyOrlov/k-turrets/files/13744374/crash-2023-12-20_22.09.27-server.txt)

**Comment by glowguy** [comment]
bump

**Comment by AlexiyOrlov** [comment]
I couldn't reproduce it and I'm ill

**Comment by AlexiyOrlov** [comment]
fixed
