### ISSUE TITLE
Game K Turret Crash -- unknown reason

### ISSUE THREAD

**Issue by glowguy** [AlexiyOrlov/k-turrets#30]
https://mclo.gs/zU9Hfd1

Forge 1.19.2 modpack crash -- crash report included

Happened exactly when the brick turret was supposed to fire at its target

**Comment by glowguy** [comment]
this has nothing to do with a previous report i submitted about lava blocking the turret. there are no obstructions and this is happening. note the mods in the modpack.

**Comment by glowguy** [comment]
another similar crash report. this keeps happening. sometimes the turrets work and then every 15 mins or so it crashes. completely unexplainable
[crash-2023-12-26_22.33.15-server.txt](https://github.com/AlexiyOrlov/k-turrets/files/13775219/crash-2023-12-26_22.33.15-server.txt)

**Comment by glowguy** [comment]
Also happened on a new world file. I wanted to make sure it wasn't a world issue.

**Comment by AlexiyOrlov** [comment]
fixed
