### ISSUE TITLE
[1.16.5] Trash lettering replaces armor bar when viewing turret radar

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#31]
Whilst holding down the key to detect if turrets are nearby, unknown letters from the UI atlas replace the armor bar for some reason.  If the button is not held, the armor bar appears fixed.

![2023-12-27_13 10 11](https://github.com/AlexiyOrlov/k-turrets/assets/82226641/bca5722d-597c-41ff-a513-76128976ab54)

**Comment by AlexiyOrlov** [comment]
This can't be fixed in 1.16.5
