### ISSUE TITLE
Arrow Turrets shoot themselves

### ISSUE THREAD

**Issue by Daralexen05** [AlexiyOrlov/k-turrets#32]
The title explains it all. Arrow Turrets tend to shoot themselves on version K-Turrets-3.0.18-1.20.1.jar for 1.20.1.

**Comment by AlexiyOrlov** [comment]
I can't reproduce this. They shoot fine for me.

**Comment by AlexiyOrlov** [comment]
No response

**Comment by Daralexen05** [comment]
> No response

I am sorry for no response. I can do further testing. I have this mod with the Cursed Walking modpack, and I placed my arrow turrets in a sniper tower to shoot at Zombies and Fungal Infection: Spore mobs. They would take damage upon an arrow being fired. I cannot tell if this is due to the placement of the turret, or the Zombies or Spore mobs have thorns armour that is just not rendered. Since sometimes my Wolf or Elephant would take damage upon hitting a Zombie while not being targeted.

**Comment by AlexiyOrlov** [comment]
Is it possible for you to make a world where you can reproduce this issue and send it to me? With minimal amount of mods
