### ISSUE TITLE
[Enhancment] 1.19.2 Allow turret to stick and be moved by pistons (normal and create)

### ISSUE THREAD

**Issue by Viktordrr4** [AlexiyOrlov/k-turrets#33]
Would it be possible to add a function so the turrets can be moved by pistons (both normal and create) while being unaffected by creeper explosions pushing them?
For example, Immobile options makes it possible for pistons and sticky pistons (create ones as well) to move them. Or perhaps a third option that is like piston-movable?
Use would be to move turrets up and down and perhaps to the sides to refill stations via pistons to safely automate ammunition delivery.
No worries if not interesting, deemed necessary, or appropriate.

Edit:
Example, add option to add 100% knockback resistance to them so the explosion still damages them but does not push the.

**Comment by AlexiyOrlov** [comment]
Do you mean make them movable by sticky pistons so they stick to the piston?

**Comment by Viktordrr4** [comment]
Yes, so they can be moved but also immune to creeper explosions and such.

**Comment by AlexiyOrlov** [comment]
I looked at the code and unfortunately, this is not possible. I can make turrets immune to explosions, but that would also disable damage from explosion.

**Comment by Viktordrr4** [comment]
Thank you for checking!
Will just have to consider it an obstacle to overcome when designing turret towers/positions then.
