### ISSUE TITLE
Turrets shoot at tamed lycanites mobs

### ISSUE THREAD

**Issue by Jetpack-Cat** [AlexiyOrlov/k-turrets#6]
Is there anything you can do to exclude tamed mobs from the firing list? These lycanites mobs are normally hostile so I don't want to exclude them from the list of who to attack, but they can alse be tamed.

**Comment by AlexiyOrlov** [comment]
I don't think I can. But if you put yourself in a team, then turrets shouldn't attack mobs that are on the owner's team. I also have an interface in my library that aims to resolve such issue - [link](https://github.com/AlexiyOrlov/satako/blob/cafe949367f9dffb2f99689057049523cdc5f44b/src/main/java/dev/buildtool/satako/Ownable.java) - it can be implemented by a mod maker on their entities.

**Comment by AlexiyOrlov** [comment]
Can't fix.
