### ISSUE TITLE
my server crashed when i attack the turrets

### ISSUE THREAD

**Issue by lonekyller** [AlexiyOrlov/k-turrets#7]
When i'am use  **<item:create_things_and_misc:spout_gun_lava>** to attack the turrets ,server crashed
[crash-2022-09-01_21.05.36-server.txt](https://github.com/AlexiyOrlov/k-turrets/files/9470514/crash-2022-09-01_21.05.36-server.txt)
here is my server 
[`https://mega.nz/file/Q4dgGQBC#_TcTj-4q5kJHjwT2GDmQFEqTlPQKAtI-va3Cc3qkcQU`](url)

**Comment by AlexiyOrlov** [comment]
Closing as outdated
